# Modelo para prever falha de maquinas num parque fabril

## Configurações do projeto

**Importar as bibliotecas e pacotes**

In [7]:
import pandas as pd
import numpy as np

**Lê arquivo com os dados**

In [12]:
file_id = "1er0sPjY51RymKrRkzZkjFOVwJ8PEZoAZ"

download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

df = pd.read_csv(download_url, sep=",", encoding="latin-1")

**Primeira visualização dos dados**

In [13]:
df.head()

,udi,id_produto,tipo,temperatura_ar_k,temperatura_processo_k,velocidade_rotacao_rpm,torque_nm,desgaste_ferramenta_min,falha_maquina,falha_twf,falha_hdf,falha_pwf,falha_osf,falha_rnf
0,1,M14860,M,298.1,308.6,1551.0,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408.0,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498.0,49.4,5,0,0,0,0,0,0
3,4,L47183,L,NaN,NaN,NaN,NaN,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408.0,40.0,9,0,0,0,0,0,0

Podemos ver que a leitura do csv ocorreu de forma correta. As colunas estão preenchidas com valores que fazem sentido para cada um dos seus significados

## Fase 1: Análise Exploratória (EDA)

**Dimensões do dataset**

In [14]:
df.shape

(10000, 14)

A função `shape`  retorna o número de linhas e colunas. Podemos ver que no caso desse dataframe temos 10000 linhas e 14 colunas

**Tipos dos dados**

In [15]:
df.dtypes

udi                          int64
id_produto                  object
tipo                        object
temperatura_ar_k           float64
temperatura_processo_k     float64
velocidade_rotacao_rpm     float64
torque_nm                  float64
desgaste_ferramenta_min      int64
falha_maquina                int64
falha_twf                    int64
falha_hdf                    int64
falha_pwf                    int64
falha_osf                    int64
falha_rnf                    int64
dtype: object

O conjunto possui:
- 1 coluna de identificação
- 2 variáveis categóricas nominais (id_produto e tipo).
- 4 variáveis numéricas contínuas.
- 1 variável numérica discreta relacionada ao desgaste da ferramenta.
- 6 variaveis numericas discretas que são variáveis binárias (0/1).

**Resumo das colunas numéricas**

In [16]:
df.describe()

,udi,temperatura_ar_k,temperatura_processo_k,velocidade_rotacao_rpm,torque_nm,desgaste_ferramenta_min,falha_maquina,falha_twf,falha_hdf,falha_pwf,falha_osf,falha_rnf
count,10000.00000,9500.000000,9500.000000,9500.000000,9500.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.002158,310.000895,1539.245263,39.974168,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.001689,1.486432,180.273589,9.995453,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.100000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1504.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1613.000000,46.700000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000